name: ci

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'docker'
        type: choice
        options:
          - docker
          - ansible

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            asdmx/mywebrepo:latest_v${{ github.run_number }}
            asdmx/mywebrepo:latest
      
      - name: Create SSM association via CLI
        id: ansible
        run: |
          aws ssm create-association \
            --name "AWS-ApplyAnsiblePlaybooks" \
            --targets Key=tag:Name,Values=webInstance \
            --parameters '{
                "SourceType": ["GitHub"],
                "SourceInfo": ["{\"owner\":\"${{ github.repository_owner }}\", \"repository\":\"${{ github.event.repository.name }}\", \"path\":\"ansible\", \"getOptions\":\"branch:master\"}"],
                "InstallDependencies": ["False"],
                "PlaybookFile": ["/roles/CD/tasks/main.yml"],
                "Check": ["False"],
                "Verbose": ["-v"],
                "TimeoutSeconds": ["3600"]
                }' \
              --association-name "Ansible-Playbook-Association"
